runtime: nodejs20
handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\.(json|ico|js|html|png))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|html|png)$
  - url: .*
    static_files: build/index.html
    upload: build/index.html

